name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Check codestyle
        run: git ls-files *.{cpp,hpp} | xargs clang-format -i && git diff --exit-code

      - name: CMake build 
        run: cmake -S . -B build/
      
      - name: Build app and test
        run: cmake --build build/
      
      - name: Run test
        run: ./build/test_list